version: '3.8'

services:
  # 데이터베이스 서비스
  postgres:
    image: postgres:14-alpine
    container_name: POPDCU-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: popdcu_db
    ports:
      - "5433:5432"  # PostgreSQL 외부 포트를 5433으로 변경
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - popdcu-network

  # 데이터베이스 관리 도구
  pgadmin:
    image: dpage/pgadmin4
    container_name: POPDCU-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"  # pgAdmin 외부 포트를 5051로 설정
    depends_on:
      - postgres
    networks:
      - popdcu-network
      
  # 백엔드 서비스
  backend:
    build: 
      context: ../POPDCU_Back/POPDCU-Back
      dockerfile: Dockerfile
    container_name: POPDCU-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/popdcu_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - popdcu-network
  
  # 프론트엔드 서비스
  frontend:
    build:
      context: ../POPDCU_Front
      dockerfile: Dockerfile
    container_name: POPDCU-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - popdcu-network

# 볼륨 설정
volumes:
  postgres_data:
  pgadmin_data:

# 네트워크 설정
networks:
  popdcu-network:
    driver: bridge
